name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: katyo/publish-crates@v2
      if: github.event_name == 'pull_requests' && github.ref == 'refs/heads/main' && success()
      with:
        dry-run: true
        ignore-unpublished-changes: true
